/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudusuarios;

import java.util.HashMap;
import java.util.InputMismatchException;
import util.Util;

/**
 *
 * @author maycon
 */
public class TelaCadastroCRUD extends javax.swing.JPanel implements java.beans.Customizer {
    
    private ControladorBean bean;
    private TelaPrincipalCRUD pai;
    private Util util;
    /**
     * Creates new customizer NovoCustomizer
     */
    public TelaCadastroCRUD(ControladorBean bean, TelaPrincipalCRUD pai) {
        initComponents();
        this.pai = pai;
        this.bean = bean;
        this.util = new Util();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNome = new javax.swing.JLabel();
        ctNome = new javax.swing.JTextField();
        lbTel = new javax.swing.JLabel();
        ctTel = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ctEmail = new javax.swing.JTextField();
        btCad = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        lbNome.setText("Nome");

        lbTel.setText("Telefone");

        jLabel1.setText("Email");

        btCad.setText("Cadastrar");
        btCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadActionPerformed(evt);
            }
        });

        jButton1.setText("Sair");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btCad)
                    .addComponent(jLabel1)
                    .addComponent(lbTel)
                    .addComponent(lbNome))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ctNome)
                    .addComponent(ctTel)
                    .addComponent(ctEmail)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNome)
                    .addComponent(ctNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTel)
                    .addComponent(ctTel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ctEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCad)
                    .addComponent(jButton1))
                .addGap(68, 68, 68))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadActionPerformed
        String nome = this.ctNome.getText();
        String telefone = ""; 
        try{
            long tel = Long.parseLong(this.ctTel.getText());
            telefone = String.valueOf(tel);
        }catch(NumberFormatException e){
            this.util.lancaExcessao("Certifique-se que o campo telefone possui apenas algarismos numéricos");
            return;
        }
        
        String email = this.ctEmail.getText();
        this.bean.cadastraUsuario(nome, telefone, email);
        this.pai.setDadosTabela(ControladorBean.getUsuarios());
        this.bean.imprimeMapa();
        this.util.lancaMessage("Usuário cadastrado com sucesso!");
    }//GEN-LAST:event_btCadActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCad;
    private javax.swing.JTextField ctEmail;
    private javax.swing.JTextField ctNome;
    private javax.swing.JTextField ctTel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbTel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setObject(Object bean) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
