/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crudusuarios;

import util.*;
import entidade.Usuario;
import java.awt.Dimension;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.TableModel;

/**
 *
 * @author maycon
 */
public class TelaPrincipalCRUD extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    private Util util;

    /**
     * Creates new customizer TelaPrincipalCRUD
     */
    public TelaPrincipalCRUD() {
        initComponents();
        TableModelUsuarios tbu = new TableModelUsuarios(null);
        this.tbUsrs = new JTable(tbu);
        this.jScrollPane2.setViewportView(tbUsrs);
        this.util = new Util();
    }

    TelaPrincipalCRUD(ControladorBean controladorBean) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }
    
    public void setDadosTabela(HashMap<Integer,Usuario> dados){
        TableModelUsuarios tbu = new TableModelUsuarios(dados);
        this.tbUsrs = new JTable(tbu);
        this.jScrollPane2.setViewportView(tbUsrs);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btCadUs = new javax.swing.JButton();
        btAltUs = new javax.swing.JButton();
        btRemUs = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbUsrs = new javax.swing.JTable();
        btSair = new javax.swing.JButton();

        btCadUs.setText("Cadastrar Usuário");
        btCadUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadUsActionPerformed(evt);
            }
        });

        btAltUs.setText("Alterar Usuário");
        btAltUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAltUsActionPerformed(evt);
            }
        });

        btRemUs.setText("Remover Usuário");
        btRemUs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemUsActionPerformed(evt);
            }
        });

        tbUsrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome", "Telefone", "Email"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbUsrs);

        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btCadUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btAltUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btRemUs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btSair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btCadUs)
                        .addGap(18, 18, 18)
                        .addComponent(btAltUs)
                        .addGap(18, 18, 18)
                        .addComponent(btRemUs)
                        .addGap(18, 18, 18)
                        .addComponent(btSair)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btCadUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadUsActionPerformed
        
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setSize(new Dimension(600, 500));
        TelaCadastroCRUD nc = new TelaCadastroCRUD(new ControladorBean(),this);
        nc.setSize(new Dimension(600, 500));
        frame.add(nc);
        frame.setVisible(true);
    }//GEN-LAST:event_btCadUsActionPerformed

    private void btAltUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAltUsActionPerformed
        JFrame frame = new JFrame();
        frame.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        frame.setSize(new Dimension(600, 500));
        int index = tbUsrs.getSelectedRow();
        Usuario usuario = ControladorBean.getUsuarios().get(index);
        HashMap<String,String> dados = new HashMap<>();
        dados.put("Código",String.valueOf(index));
        dados.put("Nome",ControladorBean.getUsuarios().get(index).getNome());
        dados.put("Telefone",ControladorBean.getUsuarios().get(index).getTelefone());
        dados.put("Email",ControladorBean.getUsuarios().get(index).getEmail());        
        TelaAlteracaoCRUD nc = new TelaAlteracaoCRUD(dados,this);
        nc.setSize(new Dimension(600, 500));
        frame.add(nc);
        frame.setVisible(true);
    }//GEN-LAST:event_btAltUsActionPerformed

    private void btRemUsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemUsActionPerformed
        int index = tbUsrs.getSelectedRow();
        if (index >= 0) {
            Usuario usuario = ControladorBean.getUsuarios().get(index);
            int resposta = util.confirm("Confirma exclusão do usuário " + usuario.getNome() + " ? ");
            if (resposta == JOptionPane.YES_OPTION) {
                try {
                    ControladorBean.removeUsuario(index);
                    util.lancaMessage("Usuário removido!");
                    this.setDadosTabela(ControladorBean.getUsuarios());
                    
                } catch (Exception e) {
                    util.lancaExcessao(e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btRemUsActionPerformed

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        
    }//GEN-LAST:event_btSairActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAltUs;
    private javax.swing.JButton btCadUs;
    private javax.swing.JButton btRemUs;
    private javax.swing.JButton btSair;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbUsrs;
    // End of variables declaration//GEN-END:variables
}
